import * as CONSTANTS from './Constants';

export default {
	PRIMARY: CONSTANTS.COLOR.RED,
	SECONDARY: CONSTANTS.COLOR.WHITE,
	MODAL_BACKGROUND: CONSTANTS.COLOR.BLACK_50,
	TERTIARY: CONSTANTS.COLOR.GRAY,
	LIST_HEADER: CONSTANTS.COLOR.GRAY_2,
	TEXT: CONSTANTS.COLOR.BLACK,
	WHITE: CONSTANTS.COLOR.WHITE,
	BLACK: CONSTANTS.COLOR.BLACK,
	WARNING: CONSTANTS.COLOR.IMPORTANT_RED,
	HIGHLIGHTED: CONSTANTS.COLOR.BLUE,
	SUB_LABEL: CONSTANTS.COLOR.BLACK_50,
	SEPARATOR: CONSTANTS.COLOR.BLACK_25,
	DISABLED: '#E1E1E1',
	FONT_SIZE: 16,
}
